apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ include "hmily-admin.fullname" . }}
  labels:
    {{- include "hmily-admin.labels" . | nindent 4 }}
data:
  application.yml: |-
    server:
      port: 8888
      servlet:
        context-path: {{ .Values.applicationConfig.server.servlet.contextPath }}
    spring:
      application:
        name: hmily-admin
      profiles:
        active: {{ .Values.dataSource.active }}
    hmily:
      admin :
        userName : {{ .Values.applicationConfig.hmily.admin.userName }}
        password : {{ .Values.applicationConfig.hmily.admin.password }}
  {{- if eq .Values.dataSource.active "mysql" }}
  application-mysql.yml: |-
    hmily:
      admin :
        retryMax : 10
        repository : mysql
        hmilyDbConfig :
          url: jdbc:mysql://{{ include "hmily-admin.fullname" . }}-mysql.{{.Release.Namespace}}.svc.cluster.local:3306/{{ required "" .Values.dataSource.mysql.database | default "hmily" }}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
          username: {{ required ".dataSource.mysql.username is required" .Values.dataSource.mysql.username }}
          password: {{ required "`dataSource.mysql.password` is required" .Values.dataSource.mysql.password }}
          driverClassName: {{ .Values.dataSource.mysql.driverClass }}
  {{- end }}
